# Ampliación de Inteligencia Artificial.
# Grado en Ingeniería Informática - Tecnologías Informáticas
# credito.py

# Contiene una serie de datos sobre concesión de créditos en una entidad
# bancaria, en función de:

# * Tipo de empleo: funcionario, contrato laboral, parado o jubilado
# * Productos finacieros contratados en la misma entidad: 0, 1 o más de 2.
# * Propiedades inmobiliarias: 0,1 o más de 2.
# * Número de hijos: 0, 1 o más de 2.
# * Estado civil: soltero, casao, viudo, divorciado. 
# * Ingresos: bajos, medios, altos

# El atributo de clasificación indica si se concede o no el crédito
# solicitado: 'conceder', 'no conceder', 'estudiar'


datos_con_clas=[['jubilado','ninguno','ninguna','uno','soltero','altos','estudiar'],
      ['funcionario','dos o más','ninguna','uno','viudo','bajos','no conceder'],
      ['parado','dos o más','dos o más','uno','divorciado','bajos','estudiar'],
      ['funcionario','dos o más','ninguna','dos o más','divorciado','altos','conceder'],
      ['funcionario','uno','dos o más','dos o más','soltero','altos','conceder'],
      ['parado','ninguno','dos o más','dos o más','divorciado','altos','conceder'],
      ['funcionario','ninguno','ninguna','uno','viudo','altos','conceder'],
      ['jubilado','ninguno','ninguna','dos o más','divorciado','altos','estudiar'],
      ['funcionario','ninguno','una','uno','soltero','bajos','estudiar'],
      ['funcionario','uno','una','ninguno','divorciado','altos','conceder'],
      ['parado','dos o más','ninguna','uno','casado','bajos','estudiar'],
      ['funcionario','ninguno','una','ninguno','viudo','bajos','estudiar'],
      ['funcionario','uno','dos o más','uno','divorciado','medios','conceder'],
      ['jubilado','dos o más','dos o más','uno','divorciado','medios','conceder'],
      ['laboral','uno','dos o más','dos o más','soltero','bajos','no conceder'],
      ['jubilado','dos o más','ninguna','dos o más','divorciado','medios','no conceder'],
      ['jubilado','dos o más','una','uno','casado','medios','no conceder'],
      ['funcionario','dos o más','dos o más','uno','soltero','medios','conceder'],
      ['jubilado','uno','ninguna','uno','soltero','medios','no conceder'],
      ['funcionario','uno','dos o más','dos o más','casado','altos','conceder'],
      ['laboral','uno','ninguna','ninguno','divorciado','medios','conceder'],
      ['jubilado','ninguno','una','ninguno','divorciado','medios','estudiar'],
      ['laboral','uno','ninguna','dos o más','soltero','medios','no conceder'],
      ['parado','uno','dos o más','dos o más','soltero','bajos','conceder'],
      ['laboral','dos o más','una','ninguno','divorciado','altos','estudiar'],
      ['laboral','dos o más','ninguna','uno','viudo','bajos','estudiar'],
      ['funcionario','ninguno','dos o más','ninguno','soltero','medios','conceder'],
      ['funcionario','ninguno','una','dos o más','soltero','altos','conceder'],
      ['laboral','uno','ninguna','uno','divorciado','altos','estudiar'],
      ['jubilado','dos o más','ninguna','ninguno','soltero','altos','estudiar'],
      ['funcionario','ninguno','una','ninguno','soltero','altos','conceder'],
      ['jubilado','dos o más','ninguna','uno','casado','altos','estudiar'],
      ['laboral','dos o más','ninguna','ninguno','soltero','altos','estudiar'],
      ['jubilado','uno','dos o más','dos o más','divorciado','bajos','estudiar'],
      ['parado','uno','una','uno','divorciado','medios','estudiar'],
      ['jubilado','uno','dos o más','ninguno','soltero','medios','conceder'],
      ['jubilado','ninguno','dos o más','ninguno','casado','bajos','estudiar'],
      ['jubilado','uno','dos o más','ninguno','casado','bajos','conceder'],
      ['laboral','ninguno','dos o más','uno','casado','altos','conceder'],
      ['jubilado','uno','ninguna','uno','soltero','bajos','no conceder'],
      ['jubilado','ninguno','una','uno','viudo','altos','estudiar'],
      ['jubilado','dos o más','ninguna','uno','soltero','altos','estudiar'],
      ['funcionario','ninguno','dos o más','uno','casado','medios','conceder'],
      ['parado','uno','una','dos o más','viudo','bajos','no conceder'],
      ['jubilado','ninguno','una','uno','casado','altos','estudiar'],
      ['laboral','uno','una','ninguno','viudo','altos','conceder'],
      ['funcionario','dos o más','una','ninguno','viudo','altos','conceder'],
      ['parado','dos o más','ninguna','ninguno','viudo','altos','conceder'],
      ['laboral','ninguno','ninguna','uno','casado','medios','estudiar'],
      ['parado','ninguno','dos o más','uno','casado','bajos','no conceder'],
      ['funcionario','ninguno','dos o más','uno','divorciado','altos','conceder'],
      ['funcionario','uno','ninguna','dos o más','divorciado','medios','estudiar'],
      ['jubilado','uno','dos o más','ninguno','soltero','bajos','no conceder'],
      ['laboral','ninguno','ninguna','ninguno','viudo','medios','estudiar'],
      ['parado','ninguno','ninguna','dos o más','casado','medios','estudiar'],
      ['jubilado','uno','una','dos o más','viudo','altos','estudiar'],
      ['funcionario','ninguno','una','uno','soltero','altos','conceder'],
      ['jubilado','dos o más','una','uno','soltero','altos','estudiar'],
      ['jubilado','dos o más','ninguna','uno','casado','medios','no conceder'],
      ['jubilado','dos o más','ninguna','uno','viudo','medios','no conceder'],
      ['parado','ninguno','una','ninguno','viudo','medios','conceder'],
      ['parado','dos o más','dos o más','ninguno','divorciado','altos','conceder'],
      ['parado','ninguno','ninguna','dos o más','viudo','medios','estudiar'],
      ['funcionario','ninguno','dos o más','dos o más','viudo','altos','conceder'],
      ['jubilado','ninguno','una','dos o más','soltero','medios','no conceder'],
      ['parado','dos o más','ninguna','uno','soltero','medios','no conceder'],
      ['funcionario','ninguno','dos o más','ninguno','soltero','altos','conceder'],
      ['laboral','uno','una','uno','soltero','bajos','no conceder'],
      ['parado','dos o más','una','dos o más','casado','bajos','no conceder'],
      ['parado','dos o más','una','uno','viudo','medios','estudiar'],
      ['laboral','uno','dos o más','ninguno','divorciado','altos','conceder'],
      ['parado','ninguno','dos o más','uno','casado','altos','estudiar'],
      ['laboral','ninguno','dos o más','dos o más','soltero','bajos','no conceder'],
      ['parado','dos o más','dos o más','dos o más','viudo','bajos','no conceder'],
      ['funcionario','uno','ninguna','ninguno','divorciado','bajos','no conceder'],
      ['jubilado','dos o más','dos o más','uno','casado','medios','conceder'],
      ['funcionario','dos o más','dos o más','ninguno','casado','altos','conceder'],
      ['parado','uno','ninguna','uno','soltero','bajos','no conceder'],
      ['jubilado','dos o más','una','dos o más','viudo','altos','estudiar'],
      ['jubilado','uno','ninguna','dos o más','casado','altos','estudiar'],
      ['jubilado','ninguno','ninguna','ninguno','viudo','bajos','no conceder'],
      ['jubilado','ninguno','una','ninguno','soltero','medios','no conceder'],
      ['parado','uno','una','dos o más','soltero','bajos','no conceder'],
      ['parado','ninguno','una','ninguno','casado','altos','estudiar'],
      ['jubilado','ninguno','ninguna','uno','soltero','medios','no conceder'],
      ['laboral','uno','dos o más','uno','casado','bajos','no conceder'],
      ['laboral','dos o más','ninguna','dos o más','soltero','bajos','estudiar'],
      ['parado','ninguno','ninguna','ninguno','soltero','medios','no conceder'],
      ['laboral','ninguno','dos o más','uno','viudo','altos','conceder'],
      ['funcionario','dos o más','ninguna','uno','casado','altos','conceder'],
      ['laboral','dos o más','una','ninguno','divorciado','bajos','estudiar'],
      ['parado','dos o más','ninguna','dos o más','soltero','altos','estudiar'],
      ['laboral','ninguno','dos o más','uno','soltero','altos','conceder'],
      ['laboral','uno','dos o más','dos o más','soltero','altos','conceder'],
      ['laboral','uno','dos o más','ninguno','viudo','bajos','no conceder'],
      ['jubilado','uno','dos o más','uno','viudo','bajos','no conceder'],
      ['jubilado','uno','dos o más','ninguno','divorciado','bajos','no conceder'],
      ['jubilado','uno','dos o más','uno','divorciado','altos','estudiar'],
      ['jubilado','uno','dos o más','uno','casado','altos','estudiar'],
      ['jubilado','ninguno','dos o más','dos o más','soltero','altos','estudiar'],
      ['funcionario','ninguno','dos o más','dos o más','viudo','bajos','estudiar'],
      ['laboral','ninguno','una','dos o más','viudo','altos','conceder'],
      ['funcionario','uno','una','uno','viudo','medios','estudiar'],
      ['parado','dos o más','ninguna','uno','casado','medios','no conceder'],
      ['parado','uno','ninguna','dos o más','divorciado','altos','estudiar'],
      ['funcionario','dos o más','dos o más','ninguno','viudo','bajos','estudiar'],
      ['funcionario','uno','ninguna','dos o más','viudo','bajos','no conceder'],
      ['funcionario','ninguno','una','ninguno','divorciado','altos','conceder'],
      ['funcionario','ninguno','ninguna','dos o más','viudo','medios','estudiar'],
      ['laboral','ninguno','ninguna','ninguno','soltero','medios','estudiar'],
      ['jubilado','uno','dos o más','ninguno','casado','altos','estudiar'],
      ['parado','uno','una','uno','viudo','bajos','no conceder'],
      ['funcionario','ninguno','dos o más','ninguno','casado','medios','conceder'],
      ['funcionario','uno','dos o más','ninguno','soltero','medios','conceder'],
      ['parado','uno','una','ninguno','viudo','medios','estudiar'],
      ['laboral','dos o más','dos o más','dos o más','casado','bajos','estudiar'],
      ['laboral','dos o más','una','uno','soltero','medios','estudiar'],
      ['jubilado','ninguno','dos o más','dos o más','divorciado','medios','conceder'],
      ['funcionario','dos o más','dos o más','ninguno','divorciado','altos','conceder'],
      ['jubilado','dos o más','ninguna','uno','viudo','bajos','no conceder'],
      ['funcionario','dos o más','una','ninguno','soltero','bajos','estudiar'],
      ['jubilado','ninguno','una','dos o más','casado','altos','estudiar'],
      ['funcionario','uno','ninguna','ninguno','divorciado','medios','estudiar'],
      ['laboral','uno','una','ninguno','divorciado','medios','estudiar'],
      ['laboral','uno','dos o más','dos o más','soltero','medios','conceder'],
      ['funcionario','dos o más','dos o más','dos o más','viudo','medios','conceder'],
      ['parado','dos o más','ninguna','uno','divorciado','altos','estudiar'],
      ['parado','ninguno','dos o más','dos o más','soltero','altos','estudiar'],
      ['jubilado','ninguno','dos o más','dos o más','divorciado','bajos','no conceder'],
      ['parado','ninguno','dos o más','dos o más','divorciado','medios','conceder'],
      ['parado','ninguno','una','uno','viudo','altos','estudiar'],
      ['laboral','uno','una','ninguno','viudo','medios','estudiar'],
      ['laboral','ninguno','ninguna','dos o más','soltero','bajos','no conceder'],
      ['parado','ninguno','una','dos o más','divorciado','medios','no conceder'],
      ['laboral','uno','una','dos o más','casado','bajos','no conceder'],
      ['jubilado','ninguno','dos o más','uno','casado','altos','estudiar'],
      ['parado','dos o más','una','uno','viudo','altos','estudiar'],
      ['parado','ninguno','una','ninguno','divorciado','altos','estudiar'],
      ['laboral','uno','una','dos o más','soltero','medios','estudiar'],
      ['laboral','uno','una','uno','divorciado','medios','estudiar'],
      ['parado','dos o más','ninguna','ninguno','casado','medios','no conceder'],
      ['funcionario','dos o más','ninguna','uno','casado','bajos','no conceder'],
      ['funcionario','uno','dos o más','ninguno','soltero','bajos','conceder'],
      ['parado','dos o más','ninguna','ninguno','soltero','altos','estudiar'],
      ['funcionario','dos o más','ninguna','ninguno','viudo','bajos','no conceder'],
      ['parado','uno','ninguna','dos o más','divorciado','bajos','no conceder'],
      ['parado','ninguno','ninguna','dos o más','divorciado','medios','no conceder'],
      ['funcionario','uno','dos o más','dos o más','casado','medios','conceder'],
      ['laboral','dos o más','una','uno','soltero','bajos','estudiar'],
      ['laboral','dos o más','dos o más','uno','viudo','altos','conceder'],
      ['jubilado','dos o más','ninguna','ninguno','casado','altos','estudiar'],
      ['jubilado','ninguno','una','ninguno','divorciado','altos','estudiar'],
      ['parado','ninguno','ninguna','uno','casado','bajos','no conceder'],
      ['parado','uno','ninguna','dos o más','soltero','bajos','no conceder'],
      ['parado','ninguno','una','uno','soltero','bajos','no conceder'],
      ['laboral','ninguno','ninguna','uno','viudo','altos','conceder'],
      ['jubilado','dos o más','una','ninguno','divorciado','bajos','no conceder'],
      ['funcionario','dos o más','ninguna','dos o más','viudo','altos','conceder'],
      ['jubilado','ninguno','ninguna','uno','viudo','altos','estudiar'],
      ['funcionario','dos o más','una','dos o más','soltero','medios','no conceder'],
      ['parado','uno','ninguna','ninguno','divorciado','medios','no conceder'],
      ['jubilado','uno','dos o más','uno','viudo','medios','conceder'],
      ['jubilado','ninguno','ninguna','dos o más','viudo','bajos','no conceder'],
      ['parado','ninguno','una','ninguno','divorciado','bajos','no conceder'],
      ['funcionario','uno','dos o más','uno','viudo','altos','conceder'],
      ['jubilado','uno','una','dos o más','soltero','bajos','no conceder'],
      ['funcionario','uno','dos o más','uno','viudo','medios','conceder'],
      ['parado','dos o más','una','ninguno','soltero','altos','estudiar'],
      ['jubilado','ninguno','ninguna','ninguno','soltero','altos','estudiar'],
      ['jubilado','dos o más','dos o más','dos o más','casado','medios','conceder'],
      ['parado','dos o más','ninguna','uno','viudo','medios','no conceder'],
      ['parado','dos o más','una','uno','casado','altos','estudiar'],
      ['parado','dos o más','una','uno','divorciado','medios','estudiar'],
      ['jubilado','uno','dos o más','uno','casado','medios','conceder'],
      ['laboral','uno','dos o más','dos o más','casado','altos','conceder'],
      ['parado','ninguno','ninguna','uno','casado','medios','no conceder'],
      ['parado','ninguno','una','ninguno','soltero','altos','estudiar'],
      ['parado','ninguno','ninguna','dos o más','soltero','altos','estudiar'],
      ['parado','uno','una','uno','casado','medios','estudiar'],
      ['parado','ninguno','dos o más','uno','divorciado','bajos','no conceder'],
      ['parado','uno','dos o más','dos o más','viudo','medios','conceder'],
      ['jubilado','uno','una','dos o más','soltero','medios','estudiar'],
      ['parado','uno','ninguna','dos o más','viudo','altos','estudiar'],
      ['laboral','ninguno','una','dos o más','casado','bajos','no conceder'],
      ['jubilado','dos o más','ninguna','uno','viudo','altos','estudiar'],
      ['parado','ninguno','ninguna','uno','divorciado','bajos','no conceder'],
      ['funcionario','ninguno','ninguna','uno','divorciado','altos','conceder'],
      ['laboral','uno','una','uno','soltero','medios','estudiar'],
      ['jubilado','uno','ninguna','dos o más','soltero','medios','no conceder'],
      ['jubilado','dos o más','ninguna','dos o más','soltero','bajos','no conceder'],
      ['parado','uno','dos o más','dos o más','viudo','altos','estudiar'],
      ['parado','uno','una','uno','viudo','medios','estudiar'],
      ['funcionario','uno','dos o más','uno','casado','bajos','conceder'],
      ['laboral','uno','una','dos o más','divorciado','bajos','no conceder'],
      ['laboral','ninguno','dos o más','uno','casado','bajos','no conceder'],
      ['parado','dos o más','dos o más','ninguno','casado','medios','conceder'],
      ['parado','uno','ninguna','uno','divorciado','altos','estudiar'],
      ['laboral','uno','dos o más','uno','soltero','bajos','no conceder'],
      ['laboral','dos o más','ninguna','uno','casado','bajos','estudiar'],
      ['laboral','ninguno','ninguna','ninguno','divorciado','altos','conceder'],
      ['parado','dos o más','una','ninguno','casado','altos','estudiar'],
      ['parado','uno','una','dos o más','casado','bajos','no conceder'],
      ['funcionario','ninguno','dos o más','ninguno','soltero','bajos','conceder'],
      ['funcionario','ninguno','dos o más','uno','viudo','medios','conceder'],
      ['funcionario','dos o más','dos o más','ninguno','soltero','bajos','conceder'],
      ['parado','dos o más','ninguna','dos o más','viudo','bajos','no conceder'],
      ['jubilado','ninguno','ninguna','dos o más','soltero','medios','no conceder'],
      ['laboral','uno','una','uno','casado','altos','conceder'],
      ['parado','dos o más','ninguna','dos o más','divorciado','bajos','no conceder'],
      ['funcionario','uno','ninguna','dos o más','divorciado','bajos','no conceder'],
      ['jubilado','uno','ninguna','dos o más','divorciado','altos','estudiar'],
      ['laboral','uno','ninguna','dos o más','soltero','altos','conceder'],
      ['laboral','uno','una','uno','viudo','altos','conceder'],
      ['laboral','dos o más','ninguna','dos o más','soltero','medios','estudiar'],
      ['parado','ninguno','dos o más','uno','viudo','altos','estudiar'],
      ['jubilado','ninguno','ninguna','ninguno','casado','bajos','no conceder'],
      ['funcionario','dos o más','ninguna','dos o más','soltero','altos','conceder'],
      ['laboral','ninguno','dos o más','dos o más','casado','medios','conceder'],
      ['jubilado','uno','ninguna','uno','divorciado','bajos','no conceder'],
      ['parado','uno','ninguna','uno','soltero','altos','estudiar'],
      ['parado','dos o más','una','ninguno','viudo','altos','estudiar'],
      ['funcionario','ninguno','ninguna','dos o más','soltero','medios','estudiar'],
      ['parado','ninguno','una','dos o más','casado','bajos','no conceder'],
      ['funcionario','ninguno','una','ninguno','viudo','altos','conceder'],
      ['parado','dos o más','una','ninguno','viudo','medios','estudiar'],
      ['laboral','uno','una','ninguno','casado','bajos','no conceder'],
      ['parado','uno','dos o más','uno','divorciado','bajos','no conceder'],
      ['parado','dos o más','una','dos o más','viudo','bajos','no conceder'],
      ['parado','uno','ninguna','ninguno','soltero','medios','no conceder'],
      ['funcionario','dos o más','dos o más','ninguno','viudo','medios','conceder'],
      ['jubilado','dos o más','una','dos o más','divorciado','medios','no conceder'],
      ['parado','ninguno','ninguna','uno','divorciado','medios','no conceder'],
      ['funcionario','dos o más','dos o más','dos o más','soltero','altos','conceder'],
      ['jubilado','dos o más','dos o más','dos o más','viudo','bajos','no conceder'],
      ['parado','uno','ninguna','dos o más','casado','altos','estudiar'],
      ['parado','ninguno','dos o más','ninguno','soltero','bajos','no conceder'],
      ['parado','uno','dos o más','ninguno','casado','medios','conceder'],
      ['funcionario','dos o más','dos o más','uno','divorciado','medios','conceder'],
      ['funcionario','dos o más','dos o más','uno','viudo','bajos','conceder'],
      ['laboral','ninguno','una','uno','soltero','altos','conceder'],
      ['funcionario','uno','una','uno','soltero','bajos','estudiar'],
      ['funcionario','ninguno','una','ninguno','soltero','bajos','estudiar'],
      ['parado','uno','ninguna','dos o más','casado','medios','no conceder'],
      ['jubilado','uno','ninguna','dos o más','viudo','bajos','no conceder'],
      ['jubilado','ninguno','ninguna','uno','viudo','bajos','no conceder'],
      ['parado','uno','dos o más','ninguno','soltero','bajos','no conceder'],
      ['laboral','dos o más','una','dos o más','soltero','bajos','estudiar'],
      ['laboral','ninguno','una','ninguno','soltero','medios','no conceder'],
      ['laboral','dos o más','dos o más','ninguno','casado','medios','conceder'],
      ['laboral','dos o más','una','ninguno','divorciado','medios','estudiar'],
      ['laboral','ninguno','dos o más','dos o más','divorciado','altos','conceder'],
      ['jubilado','ninguno','ninguna','dos o más','casado','altos','estudiar'],
      ['parado','uno','una','uno','casado','altos','estudiar'],
      ['funcionario','dos o más','ninguna','ninguno','viudo','medios','estudiar'],
      ['laboral','uno','dos o más','uno','viudo','altos','conceder'],
      ['laboral','ninguno','ninguna','ninguno','casado','medios','estudiar'],
      ['funcionario','dos o más','ninguna','dos o más','casado','altos','conceder'],
      ['parado','uno','una','ninguno','soltero','bajos','no conceder'],
      ['funcionario','dos o más','dos o más','ninguno','casado','medios','conceder'],
      ['laboral','ninguno','ninguna','uno','divorciado','altos','conceder'],
      ['funcionario','dos o más','dos o más','uno','divorciado','altos','conceder'],
      ['laboral','uno','una','ninguno','soltero','bajos','no conceder'],
      ['funcionario','dos o más','dos o más','dos o más','viudo','bajos','conceder'],
      ['laboral','ninguno','dos o más','ninguno','divorciado','altos','conceder'],
      ['jubilado','uno','una','uno','viudo','medios','estudiar'],
      ['parado','dos o más','una','uno','casado','medios','estudiar'],
      ['laboral','ninguno','ninguna','ninguno','casado','bajos','no conceder'],
      ['laboral','uno','dos o más','dos o más','casado','medios','conceder'],
      ['funcionario','ninguno','una','uno','soltero','medios','no conceder'],
      ['funcionario','uno','dos o más','uno','casado','medios','conceder'],
      ['jubilado','dos o más','una','dos o más','casado','bajos','no conceder'],
      ['parado','dos o más','ninguna','dos o más','casado','medios','no conceder'],
      ['parado','ninguno','una','dos o más','casado','medios','no conceder'],
      ['jubilado','uno','una','ninguno','casado','medios','estudiar'],
      ['funcionario','dos o más','una','ninguno','soltero','altos','conceder'],
      ['jubilado','uno','una','dos o más','soltero','altos','estudiar'],
      ['funcionario','dos o más','ninguna','uno','soltero','bajos','no conceder'],
      ['jubilado','dos o más','dos o más','ninguno','soltero','bajos','no conceder'],
      ['funcionario','dos o más','dos o más','uno','soltero','bajos','conceder'],
      ['laboral','dos o más','una','uno','divorciado','medios','estudiar'],
      ['laboral','uno','una','uno','soltero','altos','conceder'],
      ['funcionario','uno','dos o más','uno','casado','altos','conceder'],
      ['funcionario','dos o más','ninguna','uno','soltero','medios','estudiar'],
      ['funcionario','ninguno','ninguna','uno','casado','bajos','no conceder'],
      ['parado','ninguno','ninguna','uno','casado','altos','estudiar'],
      ['laboral','ninguno','una','uno','divorciado','bajos','no conceder'],
      ['parado','ninguno','ninguna','uno','divorciado','altos','estudiar'],
      ['jubilado','dos o más','dos o más','dos o más','divorciado','bajos','no conceder'],
      ['jubilado','ninguno','dos o más','uno','viudo','medios','conceder'],
      ['laboral','dos o más','una','dos o más','divorciado','altos','conceder'],
      ['laboral','dos o más','una','uno','divorciado','altos','conceder'],
      ['funcionario','ninguno','ninguna','dos o más','divorciado','bajos','no conceder'],
      ['parado','ninguno','una','uno','casado','altos','estudiar'],
      ['jubilado','ninguno','ninguna','ninguno','soltero','bajos','no conceder'],
      ['parado','dos o más','ninguna','ninguno','divorciado','medios','no conceder'],
      ['jubilado','uno','una','ninguno','soltero','altos','estudiar'],
      ['laboral','uno','dos o más','uno','divorciado','medios','conceder'],
      ['laboral','ninguno','una','ninguno','divorciado','altos','conceder'],
      ['laboral','dos o más','dos o más','ninguno','soltero','medios','conceder'],
      ['parado','uno','dos o más','ninguno','divorciado','altos','estudiar'],
      ['parado','ninguno','ninguna','dos o más','divorciado','altos','estudiar'],
      ['funcionario','ninguno','una','ninguno','divorciado','bajos','estudiar'],
      ['laboral','ninguno','ninguna','dos o más','viudo','bajos','no conceder'],
      ['jubilado','ninguno','una','ninguno','viudo','bajos','no conceder'],
      ['jubilado','ninguno','dos o más','dos o más','casado','altos','estudiar'],
      ['jubilado','dos o más','dos o más','uno','soltero','altos','estudiar'],
      ['laboral','ninguno','dos o más','dos o más','divorciado','bajos','no conceder'],
      ['jubilado','dos o más','dos o más','ninguno','viudo','bajos','no conceder'],
      ['parado','ninguno','una','uno','viudo','medios','no conceder'],
      ['jubilado','ninguno','dos o más','uno','casado','medios','conceder'],
      ['parado','ninguno','ninguna','uno','viudo','altos','estudiar'],
      ['funcionario','uno','dos o más','dos o más','viudo','bajos','conceder'],
      ['jubilado','uno','una','ninguno','viudo','medios','estudiar'],
      ['jubilado','dos o más','una','dos o más','viudo','bajos','no conceder'],
      ['jubilado','dos o más','una','ninguno','divorciado','altos','estudiar'],
      ['laboral','dos o más','una','dos o más','viudo','medios','no conceder'],
      ['parado','dos o más','dos o más','dos o más','soltero','medios','conceder'],
      ['jubilado','uno','ninguna','ninguno','divorciado','medios','no conceder'],
      ['laboral','uno','ninguna','dos o más','casado','altos','conceder'],
      ['parado','dos o más','ninguna','ninguno','casado','bajos','no conceder'],
      ['laboral','dos o más','una','uno','soltero','altos','conceder'],
      ['laboral','ninguno','dos o más','uno','viudo','medios','conceder'],
      ['laboral','ninguno','ninguna','uno','viudo','medios','estudiar'],
      ['funcionario','ninguno','dos o más','dos o más','divorciado','bajos','conceder'],
      ['jubilado','ninguno','ninguna','dos o más','viudo','medios','no conceder'],
      ['parado','uno','ninguna','ninguno','casado','bajos','no conceder'],
       ['laboral','uno','ninguna','ninguno','viudo','medios','estudiar'],
       ['funcionario','ninguno','ninguna','ninguno','divorciado','altos','conceder'],
       ['laboral','ninguno','una','ninguno','divorciado','medios','no conceder'],
       ['parado','dos o más','una','dos o más','casado','medios','no conceder'],
       ['parado','uno','una','ninguno','divorciado','medios','estudiar'],
       ['laboral','ninguno','dos o más','dos o más','viudo','bajos','no conceder'],
       ['funcionario','dos o más','una','ninguno','viudo','bajos','estudiar'],
       ['funcionario','dos o más','una','ninguno','casado','altos','conceder'],
       ['laboral','dos o más','ninguna','dos o más','viudo','altos','conceder'],
       ['laboral','uno','ninguna','ninguno','viudo','bajos','no conceder'],
       ['funcionario','dos o más','dos o más','uno','viudo','altos','conceder'],
       ['laboral','uno','dos o más','dos o más','viudo','altos','conceder'],
       ['laboral','dos o más','una','uno','viudo','altos','conceder'],
       ['parado','uno','una','dos o más','soltero','medios','estudiar'],
       ['jubilado','ninguno','una','dos o más','viudo','bajos','no conceder'],
       ['funcionario','ninguno','dos o más','uno','divorciado','bajos','conceder'],
       ['parado','uno','una','ninguno','viudo','altos','estudiar'],
       ['parado','dos o más','una','ninguno','divorciado','bajos','no conceder'],
       ['jubilado','dos o más','una','uno','soltero','bajos','no conceder'],
       ['funcionario','ninguno','dos o más','ninguno','casado','altos','conceder'],
       ['jubilado','ninguno','ninguna','ninguno','casado','altos','estudiar'],
       ['funcionario','dos o más','una','dos o más','divorciado','medios','no conceder'],
       ['funcionario','uno','ninguna','uno','soltero','altos','conceder'],
       ['parado','dos o más','dos o más','ninguno','viudo','bajos','no conceder'],
       ['laboral','ninguno','ninguna','ninguno','divorciado','bajos','no conceder'],
       ['funcionario','dos o más','ninguna','uno','viudo','medios','estudiar'],
       ['parado','uno','una','dos o más','divorciado','bajos','no conceder'],
       ['laboral','dos o más','dos o más','uno','soltero','altos','conceder'],
       ['parado','dos o más','ninguna','ninguno','soltero','medios','no conceder'],
       ['funcionario','uno','ninguna','uno','soltero','medios','estudiar'],
       ['funcionario','ninguno','ninguna','dos o más','soltero','altos','conceder'],
       ['funcionario','uno','dos o más','ninguno','casado','medios','conceder'],
       ['funcionario','dos o más','ninguna','ninguno','divorciado','bajos','no conceder'],
       ['parado','ninguno','una','dos o más','casado','altos','estudiar'],
       ['jubilado','ninguno','ninguna','dos o más','casado','bajos','no conceder'],
       ['parado','uno','una','ninguno','casado','altos','estudiar'],
       ['laboral','dos o más','una','ninguno','soltero','medios','estudiar'],
       ['parado','ninguno','dos o más','ninguno','viudo','medios','conceder'],
       ['funcionario','uno','una','uno','casado','medios','estudiar'],
       ['laboral','uno','dos o más','ninguno','casado','medios','conceder'],
       ['jubilado','uno','una','uno','divorciado','medios','estudiar'],
       ['parado','uno','dos o más','ninguno','viudo','medios','conceder'],
       ['laboral','dos o más','ninguna','dos o más','viudo','medios','estudiar'],
       ['funcionario','ninguno','dos o más','uno','viudo','altos','conceder'],
       ['jubilado','dos o más','ninguna','ninguno','viudo','bajos','no conceder'],
       ['jubilado','uno','dos o más','uno','divorciado','bajos','no conceder'],
       ['funcionario','uno','dos o más','uno','viudo','bajos','conceder'],
       ['jubilado','dos o más','ninguna','ninguno','casado','bajos','no conceder'],
       ['jubilado','uno','una','uno','divorciado','bajos','no conceder'],
       ['laboral','ninguno','dos o más','uno','soltero','medios','conceder'],
       ['laboral','dos o más','ninguna','uno','viudo','altos','conceder'],
       ['laboral','dos o más','ninguna','uno','divorciado','altos','conceder'],
       ['jubilado','uno','ninguna','uno','casado','bajos','no conceder'],
       ['parado','dos o más','una','ninguno','soltero','medios','estudiar'],
       ['jubilado','ninguno','dos o más','uno','viudo','bajos','no conceder'],
       ['parado','dos o más','dos o más','dos o más','divorciado','medios','conceder'],
       ['jubilado','dos o más','dos o más','dos o más','casado','bajos','no conceder'],
       ['jubilado','uno','dos o más','ninguno','casado','medios','conceder'],
       ['parado','uno','dos o más','dos o más','soltero','medios','conceder'],
       ['parado','uno','dos o más','dos o más','casado','medios','conceder'],
       ['jubilado','dos o más','dos o más','uno','viudo','bajos','no conceder'],
       ['parado','ninguno','una','dos o más','soltero','altos','estudiar'],
       ['funcionario','dos o más','ninguna','ninguno','casado','medios','estudiar'],
       ['laboral','dos o más','dos o más','dos o más','casado','medios','conceder'],
       ['funcionario','uno','una','ninguno','viudo','altos','conceder'],
       ['jubilado','ninguno','una','dos o más','viudo','medios','no conceder'],
       ['jubilado','dos o más','dos o más','ninguno','soltero','medios','conceder'],
       ['parado','dos o más','dos o más','ninguno','casado','bajos','no conceder'],
       ['parado','uno','ninguna','ninguno','soltero','bajos','no conceder'],
       ['laboral','dos o más','ninguna','dos o más','divorciado','altos','conceder'],
       ['jubilado','ninguno','ninguna','uno','casado','altos','estudiar'],
       ['funcionario','uno','ninguna','ninguno','casado','bajos','no conceder'],
       ['jubilado','uno','dos o más','uno','soltero','bajos','no conceder'],
       ['jubilado','dos o más','una','ninguno','soltero','altos','estudiar'],
       ['jubilado','ninguno','dos o más','dos o más','soltero','medios','conceder'],
       ['funcionario','ninguno','una','dos o más','casado','bajos','estudiar'],
       ['jubilado','dos o más','dos o más','ninguno','divorciado','medios','conceder'],
       ['funcionario','uno','una','dos o más','soltero','bajos','estudiar'],
       ['jubilado','dos o más','ninguna','ninguno','soltero','medios','no conceder'],
       ['laboral','uno','una','dos o más','casado','altos','conceder'],
       ['laboral','dos o más','una','dos o más','soltero','medios','no conceder'],
       ['jubilado','dos o más','ninguna','ninguno','casado','medios','no conceder'],
       ['parado','ninguno','una','dos o más','viudo','altos','estudiar'],
       ['funcionario','dos o más','una','uno','divorciado','medios','estudiar'],
       ['jubilado','uno','dos o más','dos o más','viudo','bajos','no conceder'],
       ['laboral','dos o más','dos o más','dos o más','divorciado','medios','conceder'],
       ['funcionario','dos o más','una','uno','viudo','medios','estudiar'],
       ['jubilado','ninguno','una','uno','soltero','bajos','no conceder'],
       ['funcionario','dos o más','ninguna','dos o más','soltero','bajos','no conceder'],
       ['laboral','ninguno','una','ninguno','soltero','altos','conceder'],
       ['laboral','ninguno','una','ninguno','casado','altos','conceder'],
       ['jubilado','dos o más','una','uno','soltero','medios','estudiar'],
       ['funcionario','uno','ninguna','uno','viudo','bajos','no conceder'],
       ['jubilado','dos o más','una','dos o más','casado','altos','estudiar'],
       ['parado','ninguno','dos o más','dos o más','viudo','altos','estudiar'],
       ['jubilado','ninguno','dos o más','ninguno','soltero','altos','estudiar'],
       ['funcionario','ninguno','una','ninguno','casado','bajos','estudiar'],
       ['jubilado','dos o más','dos o más','dos o más','viudo','altos','estudiar'],
       ['funcionario','uno','ninguna','uno','casado','medios','estudiar'],
       ['funcionario','uno','una','dos o más','casado','medios','estudiar'],
       ['jubilado','uno','ninguna','dos o más','divorciado','medios','no conceder'],
       ['parado','dos o más','una','dos o más','soltero','bajos','no conceder'],
       ['parado','uno','dos o más','uno','viudo','medios','conceder'],
       ['jubilado','ninguno','ninguna','uno','divorciado','altos','estudiar'],
       ['funcionario','dos o más','ninguna','ninguno','soltero','medios','estudiar'],
       ['funcionario','dos o más','una','dos o más','viudo','altos','conceder'],
       ['funcionario','ninguno','dos o más','dos o más','viudo','medios','conceder'],
       ['funcionario','ninguno','ninguna','ninguno','divorciado','bajos','no conceder'],
       ['laboral','ninguno','una','uno','casado','medios','no conceder'],
       ['funcionario','ninguno','dos o más','dos o más','soltero','medios','conceder'],
       ['laboral','uno','una','uno','divorciado','bajos','no conceder'],
       ['jubilado','dos o más','ninguna','dos o más','viudo','altos','estudiar'],
       ['parado','dos o más','una','dos o más','casado','altos','estudiar'],
       ['parado','dos o más','una','dos o más','soltero','medios','no conceder'],
       ['laboral','ninguno','ninguna','dos o más','casado','altos','conceder'],
       ['laboral','ninguno','una','dos o más','viudo','medios','no conceder'],
       ['jubilado','uno','ninguna','uno','divorciado','altos','estudiar'],
       ['funcionario','dos o más','dos o más','ninguno','divorciado','medios','conceder'],
       ['funcionario','dos o más','una','uno','viudo','bajos','estudiar'],
       ['parado','uno','dos o más','ninguno','soltero','altos','estudiar'],
       ['parado','uno','ninguna','ninguno','divorciado','altos','estudiar'],
       ['laboral','ninguno','dos o más','ninguno','divorciado','bajos','no conceder'],
       ['parado','uno','dos o más','dos o más','viudo','bajos','no conceder'],
       ['laboral','dos o más','ninguna','ninguno','soltero','bajos','estudiar'],
       ['parado','ninguno','una','uno','soltero','medios','no conceder'],
       ['parado','dos o más','ninguna','ninguno','viudo','medios','no conceder'],
       ['laboral','dos o más','una','uno','casado','medios','estudiar'],
       ['jubilado','dos o más','dos o más','ninguno','soltero','altos','estudiar'],
       ['jubilado','dos o más','ninguna','dos o más','casado','altos','estudiar'],
       ['laboral','ninguno','dos o más','ninguno','soltero','bajos','no conceder'],
       ['funcionario','dos o más','ninguna','uno','divorciado','medios','estudiar'],
       ['parado','uno','ninguna','ninguno','casado','medios','no conceder'],
       ['laboral','ninguno','ninguna','ninguno','divorciado','medios','estudiar'],
       ['laboral','dos o más','una','uno','casado','altos','conceder'],
       ['parado','ninguno','dos o más','ninguno','casado','medios','conceder'],
       ['jubilado','dos o más','ninguna','uno','divorciado','medios','no conceder'],
       ['parado','ninguno','una','ninguno','divorciado','medios','no conceder'],
       ['laboral','dos o más','una','ninguno','soltero','altos','conceder'],
       ['jubilado','dos o más','dos o más','dos o más','soltero','altos','estudiar'],
       ['funcionario','dos o más','una','dos o más','soltero','bajos','estudiar'],
       ['funcionario','ninguno','una','uno','casado','medios','no conceder'],
       ['laboral','uno','una','ninguno','casado','medios','estudiar'],
       ['jubilado','uno','ninguna','dos o más','viudo','medios','no conceder'],
       ['parado','dos o más','dos o más','ninguno','soltero','altos','estudiar'],
       ['funcionario','dos o más','dos o más','uno','soltero','altos','conceder'],
       ['jubilado','uno','ninguna','uno','divorciado','medios','no conceder'],
       ['funcionario','ninguno','ninguna','uno','soltero','altos','conceder'],
       ['funcionario','dos o más','dos o más','ninguno','soltero','altos','conceder'],
       ['jubilado','uno','una','ninguno','viudo','altos','estudiar'],
       ['laboral','ninguno','ninguna','dos o más','divorciado','medios','estudiar'],
       ['parado','uno','dos o más','ninguno','viudo','altos','estudiar'],
       ['laboral','ninguno','una','uno','soltero','medios','no conceder'],
       ['laboral','uno','una','dos o más','soltero','bajos','no conceder'],
       ['laboral','dos o más','una','uno','casado','bajos','estudiar'],
       ['funcionario','uno','una','uno','viudo','altos','conceder'],
       ['parado','ninguno','dos o más','ninguno','divorciado','bajos','no conceder'],
       ['laboral','uno','ninguna','ninguno','casado','bajos','no conceder'],
       ['funcionario','ninguno','dos o más','dos o más','casado','medios','conceder'],
       ['laboral','uno','dos o más','uno','divorciado','altos','conceder'],
       ['laboral','dos o más','dos o más','uno','divorciado','bajos','estudiar'],
       ['funcionario','uno','dos o más','ninguno','viudo','bajos','conceder'],
      ['funcionario','ninguno','dos o más','ninguno','divorciado','medios','conceder'],
      ['funcionario','uno','dos o más','dos o más','divorciado','bajos','conceder'],
      ['laboral','dos o más','una','ninguno','casado','medios','estudiar'],
      ['jubilado','uno','ninguna','ninguno','viudo','bajos','estudiar'],
      ['laboral','dos o más','dos o más','uno','casado','medios','conceder'],
      ['laboral','dos o más','dos o más','uno','casado','altos','conceder'],
      ['parado','ninguno','una','dos o más','divorciado','altos','estudiar'],
      ['parado','uno','dos o más','uno','casado','medios','conceder'],
      ['laboral','uno','una','uno','casado','medios','estudiar'],
      ['laboral','uno','ninguna','dos o más','divorciado','bajos','no conceder'],
      ['laboral','uno','dos o más','uno','soltero','medios','conceder'],
      ['jubilado','uno','dos o más','dos o más','casado','medios','conceder'],
      ['parado','ninguno','una','uno','viudo','bajos','no conceder'],
      ['parado','dos o más','dos o más','ninguno','viudo','altos','estudiar'],
      ['funcionario','ninguno','ninguna','ninguno','soltero','medios','estudiar'],
      ['funcionario','ninguno','una','uno','viudo','bajos','estudiar'],
      ['funcionario','ninguno','ninguna','ninguno','soltero','bajos','no conceder'],
      ['jubilado','ninguno','dos o más','ninguno','soltero','bajos','no conceder'],
      ['parado','ninguno','dos o más','ninguno','divorciado','altos','estudiar'],
      ['jubilado','dos o más','dos o más','uno','casado','bajos','no conceder'],
      ['funcionario','uno','ninguna','dos o más','viudo','altos','conceder'],
      ['laboral','uno','ninguna','ninguno','divorciado','bajos','no conceder'],
      ['laboral','uno','ninguna','dos o más','soltero','bajos','no conceder'],
      ['jubilado','ninguno','una','dos o más','soltero','bajos','no conceder'],
      ['parado','ninguno','ninguna','uno','viudo','bajos','no conceder'],
      ['funcionario','uno','ninguna','ninguno','viudo','bajos','no conceder'],
      ['parado','ninguno','dos o más','dos o más','soltero','medios','conceder'],
      ['parado','ninguno','ninguna','ninguno','soltero','altos','estudiar'],
      ['parado','ninguno','dos o más','dos o más','viudo','bajos','no conceder'],
      ['jubilado','ninguno','ninguna','dos o más','soltero','altos','estudiar'],
      ['jubilado','uno','dos o más','ninguno','soltero','altos','estudiar'],
      ['parado','ninguno','dos o más','uno','casado','medios','conceder'],
      ['laboral','ninguno','dos o más','dos o más','casado','altos','conceder'],
      ['parado','uno','ninguna','uno','soltero','medios','no conceder'],
      ['laboral','ninguno','dos o más','ninguno','soltero','medios','conceder'],
      ['funcionario','uno','ninguna','dos o más','casado','altos','conceder'],
      ['funcionario','dos o más','dos o más','dos o más','divorciado','bajos','conceder'],
      ['jubilado','ninguno','una','dos o más','divorciado','bajos','no conceder'],
      ['parado','uno','dos o más','ninguno','soltero','medios','conceder'],
      ['jubilado','ninguno','ninguna','dos o más','viudo','altos','estudiar'],
      ['funcionario','dos o más','ninguna','uno','viudo','altos','conceder'],
      ['parado','ninguno','ninguna','uno','soltero','medios','no conceder'],
      ['laboral','ninguno','una','uno','soltero','bajos','no conceder'],
      ['laboral','dos o más','una','dos o más','casado','medios','no conceder'],
      ['laboral','dos o más','ninguna','ninguno','viudo','medios','estudiar'],
      ['laboral','uno','dos o más','dos o más','divorciado','bajos','no conceder'],
      ['funcionario','uno','ninguna','dos o más','soltero','medios','estudiar'],
      ['jubilado','dos o más','ninguna','ninguno','soltero','bajos','no conceder'],
      ['jubilado','dos o más','una','ninguno','casado','bajos','no conceder'],
      ['laboral','ninguno','dos o más','dos o más','soltero','altos','conceder'],
      ['funcionario','ninguno','dos o más','uno','casado','altos','conceder'],
      ['laboral','ninguno','ninguna','uno','soltero','medios','estudiar'],
      ['laboral','uno','ninguna','dos o más','divorciado','medios','estudiar'],
      ['funcionario','dos o más','una','ninguno','casado','bajos','estudiar'],
      ['laboral','dos o más','una','ninguno','viudo','bajos','estudiar'],
      ['laboral','uno','ninguna','uno','casado','altos','conceder'],
      ['jubilado','ninguno','una','dos o más','divorciado','altos','estudiar'],
      ['laboral','dos o más','dos o más','ninguno','divorciado','altos','conceder'],
      ['jubilado','uno','ninguna','ninguno','soltero','altos','estudiar'],
      ['laboral','ninguno','dos o más','ninguno','soltero','altos','conceder'],
      ['parado','dos o más','ninguna','uno','soltero','altos','estudiar'],
      ['parado','dos o más','una','ninguno','casado','medios','estudiar'],
      ['funcionario','dos o más','dos o más','dos o más','viudo','altos','conceder'],
      ['jubilado','dos o más','una','dos o más','divorciado','bajos','no conceder'],
      ['jubilado','dos o más','dos o más','ninguno','casado','medios','conceder'],
      ['laboral','uno','ninguna','uno','soltero','medios','estudiar'],
      ['laboral','uno','una','dos o más','soltero','altos','conceder'],
      ['parado','ninguno','una','ninguno','soltero','medios','estudiar'],
      ['parado','ninguno','ninguna','dos o más','soltero','medios','no conceder'],
      ['laboral','dos o más','dos o más','dos o más','viudo','bajos','estudiar'],
      ['jubilado','dos o más','una','ninguno','viudo','medios','estudiar'],
      ['funcionario','uno','dos o más','uno','soltero','medios','conceder'],
      ['jubilado','uno','dos o más','uno','soltero','medios','conceder'],
      ['parado','ninguno','una','ninguno','viudo','altos','estudiar'],
      ['parado','dos o más','ninguna','ninguno','divorciado','bajos','no conceder'],
      ['laboral','ninguno','ninguna','uno','divorciado','medios','estudiar'],
      ['funcionario','uno','dos o más','uno','divorciado','bajos','conceder'],
      ['laboral','uno','ninguna','ninguno','soltero','bajos','no conceder'],
      ['jubilado','dos o más','ninguna','dos o más','viudo','bajos','no conceder'],
      ['jubilado','ninguno','una','dos o más','casado','bajos','no conceder'],
      ['laboral','dos o más','dos o más','dos o más','divorciado','bajos','estudiar'],
      ['parado','dos o más','dos o más','ninguno','divorciado','bajos','no conceder'],
      ['laboral','dos o más','dos o más','uno','divorciado','medios','conceder'],
      ['funcionario','uno','una','dos o más','casado','bajos','estudiar'],
      ['funcionario','uno','dos o más','ninguno','divorciado','bajos','conceder'],
      ['funcionario','dos o más','ninguna','dos o más','viudo','medios','estudiar'],
      ['laboral','ninguno','ninguna','ninguno','soltero','altos','conceder'],
      ['funcionario','ninguno','dos o más','ninguno','divorciado','bajos','conceder'],
      ['parado','dos o más','dos o más','dos o más','viudo','altos','estudiar'],
      ['jubilado','dos o más','dos o más','ninguno','casado','altos','estudiar'],
      ['parado','uno','ninguna','dos o más','viudo','bajos','no conceder'],
      ['laboral','dos o más','una','uno','viudo','bajos','estudiar'],
      ['laboral','uno','ninguna','dos o más','viudo','medios','estudiar'],
      ['jubilado','ninguno','una','ninguno','viudo','medios','no conceder'],
      ['parado','uno','una','ninguno','casado','bajos','no conceder'],
      ['funcionario','uno','ninguna','uno','casado','altos','conceder'],
      ['laboral','ninguno','una','uno','divorciado','altos','conceder'],
      ['jubilado','uno','ninguna','ninguno','soltero','medios','no conceder'],
      ['funcionario','ninguno','dos o más','uno','soltero','altos','conceder'],
      ['laboral','ninguno','una','uno','casado','bajos','no conceder'],
      ['laboral','dos o más','dos o más','uno','casado','bajos','estudiar'],
      ['parado','uno','dos o más','ninguno','casado','altos','estudiar'],
      ['funcionario','dos o más','dos o más','dos o más','divorciado','altos','conceder'],
      ['jubilado','dos o más','una','uno','viudo','altos','estudiar'],
      ['laboral','uno','una','ninguno','viudo','bajos','no conceder'],
      ['funcionario','uno','una','uno','divorciado','altos','conceder'],
      ['jubilado','uno','ninguna','dos o más','viudo','altos','estudiar'],
      ['funcionario','ninguno','una','dos o más','soltero','medios','no conceder'],
      ['jubilado','uno','dos o más','ninguno','divorciado','altos','estudiar'],
      ['jubilado','ninguno','ninguna','ninguno','casado','medios','no conceder'],
      ['parado','ninguno','una','uno','divorciado','medios','no conceder'],
      ['laboral','ninguno','una','dos o más','casado','medios','no conceder'],
      ['jubilado','uno','dos o más','ninguno','divorciado','medios','conceder'],
      ['jubilado','ninguno','una','ninguno','soltero','bajos','no conceder'],
      ['parado','ninguno','una','ninguno','casado','medios','no conceder'],
      ['parado','uno','ninguna','uno','casado','medios','no conceder'],
      ['jubilado','uno','una','ninguno','soltero','bajos','no conceder'],
      ['parado','dos o más','dos o más','dos o más','casado','bajos','no conceder'],
      ['funcionario','ninguno','una','uno','viudo','medios','no conceder'],
      ['jubilado','dos o más','ninguna','dos o más','viudo','medios','no conceder'],
      ['jubilado','dos o más','dos o más','uno','viudo','altos','estudiar'],
      ['jubilado','dos o más','dos o más','dos o más','soltero','medios','conceder'],
      ['parado','dos o más','ninguna','uno','divorciado','bajos','no conceder'],
      ['laboral','dos o más','dos o más','ninguno','soltero','altos','conceder'],
      ['jubilado','ninguno','dos o más','dos o más','viudo','altos','estudiar'],
      ['laboral','uno','ninguna','ninguno','soltero','medios','estudiar'],
      ['jubilado','dos o más','ninguna','ninguno','viudo','medios','no conceder'],
      ['jubilado','ninguno','dos o más','uno','soltero','altos','estudiar'],
      ['funcionario','ninguno','ninguna','dos o más','casado','medios','estudiar'],
      ['jubilado','dos o más','ninguna','ninguno','divorciado','medios','no conceder'],
      ['parado','dos o más','ninguna','uno','casado','altos','estudiar'],
      ['jubilado','ninguno','una','uno','viudo','medios','no conceder'],
      ['parado','dos o más','dos o más','uno','soltero','medios','conceder'],
      ['jubilado','dos o más','dos o más','ninguno','viudo','medios','conceder'],
      ['jubilado','dos o más','una','ninguno','casado','medios','estudiar'],
      ['funcionario','uno','una','ninguno','casado','altos','conceder'],
      ['funcionario','uno','una','dos o más','casado','altos','conceder'],
      ['jubilado','ninguno','una','ninguno','casado','altos','estudiar'],
      ['funcionario','uno','una','ninguno','casado','medios','estudiar'],
      ['jubilado','uno','ninguna','ninguno','casado','altos','estudiar'],
      ['laboral','ninguno','una','dos o más','soltero','medios','no conceder'],
      ['funcionario','dos o más','una','ninguno','soltero','medios','estudiar'],
      ['parado','dos o más','ninguna','uno','viudo','bajos','no conceder'],
      ['funcionario','dos o más','una','uno','soltero','bajos','estudiar'],
      ['jubilado','ninguno','dos o más','dos o más','viudo','medios','conceder'],
      ['laboral','uno','ninguna','uno','soltero','altos','conceder'],
      ['laboral','ninguno','una','ninguno','casado','bajos','no conceder'],
      ['laboral','uno','ninguna','dos o más','viudo','bajos','no conceder'],
      ['laboral','uno','ninguna','ninguno','divorciado','altos','conceder'],
      ['parado','uno','dos o más','dos o más','divorciado','bajos','no conceder'],
      ['laboral','uno','una','uno','divorciado','altos','conceder'],
      ['funcionario','uno','una','uno','casado','bajos','estudiar'],
      ['funcionario','ninguno','una','uno','divorciado','bajos','estudiar'],
      ['laboral','uno','dos o más','dos o más','casado','bajos','no conceder'],
      ['parado','uno','ninguna','uno','divorciado','medios','no conceder'],
      ['laboral','uno','ninguna','uno','viudo','altos','conceder'],
      ['laboral','dos o más','una','ninguno','viudo','medios','estudiar'],
      ['parado','ninguno','ninguna','uno','soltero','altos','estudiar'],
      ['jubilado','ninguno','una','uno','casado','bajos','no conceder'],
      ['jubilado','uno','ninguna','uno','soltero','altos','estudiar'],
      ['parado','uno','dos o más','ninguno','divorciado','bajos','no conceder'],
      ['funcionario','uno','dos o más','ninguno','viudo','medios','conceder'],
      ['funcionario','dos o más','dos o más','dos o más','divorciado','medios','conceder']]
